version: 2.1

jobs:
  sample:
    docker:
      - image: cimg/node:20.12.0
      - image: cimg/ruby:3.4.2
      - image: cimg/node:20.12.0-browsers
      - image: cimg/ruby:3.4.2-browsers
    steps:
      - run: echo "ok"

workflows:
  sample:
    jobs:
      - sample
