version: 2.1

jobs:
  sample:
    docker:
      - image: cimg/node:22.14.0
      - image: cimg/ruby:3.3.5
      - image: cimg/node:22.14.0-browsers
      - image: cimg/ruby:3.3.5-browsers
    steps:
      - run: echo "ok"

workflows:
  sample:
    jobs:
      - sample
