version: 2.1

jobs:
  sample:
    docker:
      - image: cimg/node:20.12.0
      - image: cimg/ruby:4.0.6
      - image: cimg/node:20.12.0-browsers
      - image: cimg/ruby:4.0.6-browsers
    steps:
      - run: echo "ok"

workflows:
  sample:
    jobs:
      - sample
