version: 2.1

jobs:
  sample:
    docker:
      - image: cimg/node:20.18.3
      - image: cimg/ruby:3.3.5
      - image: cimg/node:20.18.3-browsers
      - image: cimg/ruby:3.3.5-browsers
    steps:
      - run: echo "ok"

workflows:
  sample:
    jobs:
      - sample
